name: Waka Readme

on:
  schedule:
    # Runs at 20:30pm UTC & 2:00am IST
    - cron: '30 20 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: apoorvtyagi # optional, it will automatically use the username of the owner of the repository who's executing the workflow.
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
